apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    {{- toYaml .Values.annotations | nindent 4}}
  labels:
    app: {{ .Values.jobName }}
    release: {{ .Release.Name }}
  name: {{ .Values.jobName }}
spec:
  activeDeadlineSeconds: {{ int .Values.activeDeadlineSeconds }}
  backoffLimit: 100
  template:
    metadata:
      {{- with merge .Values.podAnnotations .Values.commonPodAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end}}
      labels:
        app: {{ .Values.jobName }}
        release: {{ .Release.Name }}
        {{- with merge .Values.podLabels .Values.commonPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: db-schema-manager
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/opt/liquibase/liquibase"
            - "--url"
            - {{ .Values.database.url | quote }}
            - "--changeLogFile"
            - {{ .Values.changeLogFile | quote }}
            - "--username"
            - {{ .Values.database.username | quote }}
            - "--password"
            - "$(DATABASE_PASSWORD)"
            - "update"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.passwordSecretName }}
                  key: {{ .Values.database.passwordSecretKey }}
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: changelogs
              mountPath: /etc/liquibase/changelogs
              readOnly: true
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: changelogs
          configMap:
            name: {{ .Values.jobName }}
  ttlSecondsAfterFinished: {{ int .Values.ttlSecondsAfterFinished }}
